### ISSUE TITLE
Polish lang support

### ISSUE THREAD

**Issue by fejmek** [Nullent/CCProcessor#14]
[ccproc.phrases.txt](https://github.com/Nullent/CCProcessor/files/4953850/ccproc.phrases.txt)
[ccp_defmessage.phrases.txt](https://github.com/Nullent/CCProcessor/files/4953851/ccp_defmessage.phrases.txt)

:)

**Comment by IIEnt** [comment]
@fejmek Good job, can you open a pull request to the master branch?
